# Generated by Django 5.2.4 on 2025-10-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bus_no_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveBigIntegerField(),
        ),
    ]
